# https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#target-branch

version: 2

updates:
    -
        allow:
            - dependency-type: "direct"
        commit-message:
            include: "scope"
            prefix: "composer"
        directory: "/"
        labels:
            - "dependency"
            - "automerge"
        open-pull-requests-limit: 5
        package-ecosystem: "composer"
        schedule:
            interval: "daily"
        versioning-strategy: "lockfile-only"

    -
        commit-message:
            include: "scope"
            prefix: "github-actions"
        directory: "/"
        labels:
            - "dependency"
            - "automerge"
        open-pull-requests-limit: 5
        package-ecosystem: "github-actions"
        schedule:
            interval: "daily"
